version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: financial_tracker_db
    environment:
      POSTGRES_DB: money
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d money"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Financial Tracker App
  app:
    build: .
    container_name: financial_tracker_app
    env_file:
      - .env.example
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=money
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./converted_data:/app/converted_data
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev

volumes:
  postgres_data:
